name: Generate Metrics

on:
  schedule: # Executa o workflow a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_traffic: yes
          plugin_habits: yes
          config_timezone: America/Sao_Paulo
          config_padding: 16
          config_display_duration: true
